# ============================================================================
#  Résumé build
#
#    make            # full variant  -> build/resume-full.pdf
#    make short      # short variant -> build/resume-short.pdf
#    make all        # every variant
#    make VARIANT=x  # arbitrary variant name
#
#  A warning (not an error) is emitted for any PDF longer than PAGE_BUDGET
#  pages; set PAGE_BUDGET=0 to silence it.
#
#  Section-order flags (0/1, combinable):
#    make SKILLS_BOTTOM=1              # Skills after Experience/Projects
#    make EDUCATION_BOTTOM=1           # Education after Experience/Projects
#    make bottom                       # both, tagged output name
#    make watch      # rebuild on change (needs entr or fswatch)
#    make clean
#
#  Build-time values reach LaTeX through the generated build-vars.tex, which
#  resume.tex pulls in with \InputIfFileExists. Add a knob by adding a line
#  here and a matching \providecommand in resumestyle.sty.
# ============================================================================

ENGINE   ?= tectonic
VARIANT  ?= full
VARIANTS ?= full short
DATE     ?= $(shell date +%Y-%m-%d)

# Warn when a built PDF runs longer than this many pages (0 disables).
PAGE_BUDGET ?= 1

# Section-order flags: set to 1 to push that section below Experience.
SKILLS_BOTTOM    ?= 0
EDUCATION_BOTTOM ?= 0

# Output name picks up a suffix when the default order is changed.
TAG := $(VARIANT)$(if $(filter 1,$(SKILLS_BOTTOM)),-skillsbottom)$(if $(filter 1,$(EDUCATION_BOTTOM)),-edubottom)

SRC      := resume.tex
DEPS     := $(SRC) resumestyle.sty
OUT      := build
PDF      := $(OUT)/resume-$(TAG).pdf
# Sidecar describing how this PDF was built; consumed by CI for release notes.
MANIFEST := $(OUT)/resume-$(TAG).json

.PHONY: default all short full bottom watch clean print-vars
.DELETE_ON_ERROR:

default: $(PDF)

# One target per known variant: `make short`, `make full`, ...
$(VARIANTS):
	@$(MAKE) --no-print-directory VARIANT=$@

all:
	@for v in $(VARIANTS); do $(MAKE) --no-print-directory VARIANT=$$v; done

# Both sections moved below Experience.
bottom:
	@$(MAKE) --no-print-directory SKILLS_BOTTOM=1 EDUCATION_BOTTOM=1

# build-vars.tex is regenerated on every build: it carries the variant name and
# a timestamp, so it must not be cached as an up-to-date prerequisite.
$(PDF): $(DEPS)
	@mkdir -p $(OUT)
	@printf '%% generated by make -- do not edit\n' >  build-vars.tex
	@printf '\\renewcommand{\\buildvariant}{%s}\n' '$(VARIANT)' >> build-vars.tex
	@printf '\\renewcommand{\\builddate}{%s}\n'    '$(DATE)'    >> build-vars.tex
	@$(if $(filter 1,$(SKILLS_BOTTOM)),printf '\\skillsbottom\n' >> build-vars.tex,:)
	@$(if $(filter 1,$(EDUCATION_BOTTOM)),printf '\\educationbottom\n' >> build-vars.tex,:)
	$(ENGINE) $(SRC) --outdir $(OUT)
	@mv $(OUT)/resume.pdf $(PDF)
	@pages=$$(pdfinfo $(PDF) 2>/dev/null | awk '/^Pages:/{print $$2}'); \
	 bytes=$$(wc -c < $(PDF) | tr -d ' '); \
	 printf '{"file":"%s","variant":"%s","skills_bottom":%s,"education_bottom":%s,"pages":"%s","bytes":%s,"date":"%s","engine":"%s"}\n' \
	   "$$(basename $(PDF))" "$(VARIANT)" \
	   "$(if $(filter 1,$(SKILLS_BOTTOM)),true,false)" \
	   "$(if $(filter 1,$(EDUCATION_BOTTOM)),true,false)" \
	   "$${pages:-?}" "$$bytes" "$(DATE)" "$$($(ENGINE) --version | head -1)" \
	   > $(MANIFEST); \
	 if [ "$(PAGE_BUDGET)" != "0" ] && [ "$${pages:-?}" != "?" ] \
	    && [ "$$pages" -gt "$(PAGE_BUDGET)" ]; then \
	   msg="$(PDF) is $$pages pages (budget: $(PAGE_BUDGET))"; \
	   if [ -n "$$GITHUB_ACTIONS" ]; then echo "::warning title=Résumé too long::$$msg"; fi; \
	   echo "warning: $$msg" >&2; \
	 fi
	@echo "-> $(PDF)  (variant=$(VARIANT), date=$(DATE), skills_bottom=$(SKILLS_BOTTOM), education_bottom=$(EDUCATION_BOTTOM))"

print-vars:
	@echo "ENGINE=$(ENGINE) VARIANT=$(VARIANT) VARIANTS=$(VARIANTS) DATE=$(DATE) SKILLS_BOTTOM=$(SKILLS_BOTTOM) EDUCATION_BOTTOM=$(EDUCATION_BOTTOM) -> $(PDF)"

watch:
	@command -v entr >/dev/null 2>&1 \
	  && ls $(DEPS) | entr -c $(MAKE) VARIANT=$(VARIANT) \
	  || echo "install entr:  brew install entr"

clean:
	rm -rf $(OUT) build-vars.tex
